name: 'Deploy Pinafood using GH Actions to GH Pages'

on:
  pull_request:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Integratation Test Apps
        run: yarn test
